name: load-secrets
run-name: We load secrets.
steps:
  - name: OpenAI key load
    env:
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
  - name: Telegram key load
    env:
      TELEGRAM_KEY: ${{ secrets.TELEGRAM_KEY }}
